# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 449ef848e35ef3c7d406620e1c863b83cd1beed1816cd55b415d0113421012818ce3a104da9e82b29e4519b8245339ec5027ff74ff0bdcc9ce9b5c8c639f4ed1

test:
  secret_key_base: d4ff6119ee0a042e127b69c0fbf9dee11dd912dd412b38cf0c48bdaa77759f1eea4e66b1b3f3dafee5ab44cadca343ce4fee6b9f32fb2ceb43eaae6a4c095cd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
